# Koyeb configuration file for CortexaAI
# This file helps configure your deployment on Koyeb

# Build configuration
build:
  # Dockerfile path (relative to repository root)
  dockerfile: Dockerfile
  
  # Build arguments (if needed)
  # args:
  #   - BUILD_ENV=production

# Runtime configuration
run:
  # Health check endpoint
  healthcheck:
    path: /health
    interval: 30
    timeout: 10
    initialDelay: 40

# Environment variables (set these in Koyeb dashboard)
# Required:
# - GOOGLE_API_KEY or OPENAI_API_KEY (at least one LLM provider)
# Optional:
# - LANGSMITH_API_KEY (for tracing)
# - CORS_ORIGINS (comma-separated list, or leave empty for *)
# - PORT (automatically set by Koyeb)
# - HOST (defaults to 0.0.0.0)
# - ENVIRONMENT=production

# Scaling configuration (configure in Koyeb dashboard)
# - Minimum instances: 1
# - Maximum instances: as needed
# - Auto-scaling: enabled

# Resource limits (configure in Koyeb dashboard)
# - Memory: 512MB minimum (1GB recommended)
# - CPU: 0.5 vCPU minimum (1 vCPU recommended)

